name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        # create_credentials_file: true
        workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
        access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./examples/csharp
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./examples/csharp
    - name: Run
      run: dotnet run ${{ steps.auth.outputs.access_token }}
      working-directory: ./examples/csharp 
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./examples/csharp
